# Generated by Django 3.2.4 on 2021-07-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_comentariocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario Contacto', 'verbose_name_plural': 'Comentarios Contactos'},
        ),
    ]
